trigger:
- main

pr:
- main

variables:
  solutionDir: Saj.APi

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build
    jobs:
      - job: build
        steps:
          - script: pwd
            displayName: 'What directory are we in?'

          - script: ls -la
            displayName: 'What files are in this folder?'

          - script: dotnet build
            displayName: 'Dotnet build'

          - task: DotNetCoreCLI@2
            displayName: 'Run unit tests'
            inputs:
              command: test
              projects: '**/*Tests/*.csproj'

          - script: dotnet publish -o $(build.artifactStagingDirectory)
            displayName: 'Dotnet publish -o $(build.artifactStagingDirectory)'

          - task: PublishPipelineArtifact@1
            displayName: 'Publish Pipeline Artifact'
            inputs:
              targetPath: '$(build.artifactStagingDirectory)'
              artifact: 'drop'
              publishLocation: 'pipeline'
  - stage: deploy_to_prod
    jobs:
      - job: build
        steps:
          - script: pwd
            displayName: 'What directory are we in?'

          - script: ls -la
            displayName: 'What files are in this folder?'

          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: 'drop'
              targetPath: '$(Pipeline.Workspace)/drop'

          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'sajapiv3connection'
              appType: 'webApp'
              appName: 'sajapiv2'
              deployToSlotOrASE: true
              resourceGroupName: 'sajrg'
              slotName: 'production'
              package: '$(Pipeline.Workspace)/drop'
              deploymentMethod: 'auto'

